
# Cổng chạy ứng dụng
server.port=8081

# Cấu hình kết nối MySQL
# Lưu ý: 3306 là cổng mặc định, dat_tour_du_lich là tên DB
spring.datasource.url=jdbc:mysql://localhost:3306/dat_tour_du_lich?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=123456

# Cấu hình hiển thị SQL (để debug sau này)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Tăng giới hạn upload file
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cấu hình Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hoangtom976@gmail.com
spring.mail.password=mcxjahbjnkcgllmq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- CẤU HÌNH AI (GROQ) ---
groq.api.key=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
groq.api.model=llama-3.3-70b-versatile
groq.api.url=https://api.groq.com/openai/v1/chat/completions


# ===== OPENWEATHERMAP =====
openweathermap.api-key=9297f91d1fa44481b6e41436ef7ca78b
openweathermap.base-url=https://api.openweathermap.org/data/2.5/weather

# --- CẤU HÌNH HUGGINGFACE EMBEDDING ---
huggingface.embedding-url=https://router.huggingface.co/hf-inference/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/pipeline/feature-extraction
huggingface.embedding-dimension=384
huggingface.api-token=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

# --- CẤU HÌNH QDRANT ---
qdrant.host=localhost
qdrant.port=6334
qdrant.collection-name=tours
